<Project>

  <PropertyGroup>
    <TargetFrameworks>net48;net6.0;net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Authors>Patrick DeSomma</Authors>
    <PackageProjectUrl>https://github.com/pdesomma/WiiUSharp</PackageProjectUrl>
    <RepositoryUrl>https://github.com/pdesomma/WiiUSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>wiiu;wii u;nintendo</PackageTags>
  </PropertyGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <TargetFrameworks>net48;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Compile Include="$(MSBuildThisFileDirectory).build\IsExternalInit.cs" Link="Internal\IsExternalInit.cs" />
  </ItemGroup>

  <ItemGroup Condition="!$(MSBuildProjectName.EndsWith('.Tests'))">
    <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
